# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.paraphrase_text_request import ParaphraseTextRequest  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestParaphraseTextRequest(unittest.TestCase):
    """ParaphraseTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ParaphraseTextRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParaphraseTextRequest`
        """
        model = groupdocs_rewriter_cloud.models.paraphrase_text_request.ParaphraseTextRequest()  # noqa: E501
        if include_optional :
            return ParaphraseTextRequest(
                language = '0', 
                text = '', 
                texts = [
                    ''
                    ], 
                origin = '', 
                suggestions = 'One', 
                diversity_degree = 'Off', 
                tokenize = True
            )
        else :
            return ParaphraseTextRequest(
                language = '0',
        )
        """

    def testParaphraseTextRequest(self):
        """Test ParaphraseTextRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
