# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.11.1
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.api.simplify_api import SimplifyApi  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException


class TestSimplifyApi(unittest.TestCase):
    """SimplifyApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_rewriter_cloud.api.simplify_api.SimplifyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_simplify_document_post(self):
        """Test case for simplify_document_post

        Simplify document  # noqa: E501
        """
        pass

    def test_simplify_document_request_id_get(self):
        """Test case for simplify_document_request_id_get

        Return document simplifying status.  Also return URLs for downloading of simplified document if paraphrasig was successful  # noqa: E501
        """
        pass

    def test_simplify_document_trial_post(self):
        """Test case for simplify_document_trial_post

        Trial simplify document  # noqa: E501
        """
        pass

    def test_simplify_hc_get(self):
        """Test case for simplify_hc_get

        Health check for all simplify services.  # noqa: E501
        """
        pass

    def test_simplify_supported_conversions_get(self):
        """Test case for simplify_supported_conversions_get

        """
        pass

    def test_simplify_text_post(self):
        """Test case for simplify_text_post

        Simplify text  # noqa: E501
        """
        pass

    def test_simplify_text_request_id_get(self):
        """Test case for simplify_text_request_id_get

        Return text simplifying status.  Also return simplified text if paraphrasing was successful  # noqa: E501
        """
        pass

    def test_simplify_text_trial_post(self):
        """Test case for simplify_text_trial_post

        Trial simplify text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
