# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.formalize_supported_fromats import FormalizeSupportedFromats

class TestFormalizeSupportedFromats(unittest.TestCase):
    """FormalizeSupportedFromats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormalizeSupportedFromats(self):
        """Test FormalizeSupportedFromats"""
        # inst = FormalizeSupportedFromats()

if __name__ == '__main__':
    unittest.main()
