# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.11.1
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.detection_file_request import DetectionFileRequest  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestDetectionFileRequest(unittest.TestCase):
    """DetectionFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DetectionFileRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectionFileRequest`
        """
        model = groupdocs_rewriter_cloud.models.detection_file_request.DetectionFileRequest()  # noqa: E501
        if include_optional :
            return DetectionFileRequest(
                language = '0', 
                file = 'YQ==', 
                url = '', 
                origin = '', 
                original_name = '', 
                saving_mode = 'Files', 
                min_length = 56, 
                format = 'Unknown'
            )
        else :
            return DetectionFileRequest(
                language = '0',
        )
        """

    def testDetectionFileRequest(self):
        """Test DetectionFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
