# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.ocr_output_format import OcrOutputFormat

class TestOcrOutputFormat(unittest.TestCase):
    """OcrOutputFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOcrOutputFormat(self):
        """Test OcrOutputFormat"""
        # inst = OcrOutputFormat()

if __name__ == '__main__':
    unittest.main()
