# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.media_input_format import MediaInputFormat

class TestMediaInputFormat(unittest.TestCase):
    """MediaInputFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaInputFormat(self):
        """Test MediaInputFormat"""
        # inst = MediaInputFormat()

if __name__ == '__main__':
    unittest.main()
