# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.api.compare_api import CompareApi


class TestCompareApi(unittest.TestCase):
    """CompareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompareApi()

    def tearDown(self) -> None:
        pass

    def test_compare_hc_get(self) -> None:
        """Test case for compare_hc_get

        Health check for all comparer services.
        """
        pass

    def test_compare_text_post(self) -> None:
        """Test case for compare_text_post

        Compare texts and detect if one is translation or paraphrase of another
        """
        pass

    def test_compare_text_request_id_get(self) -> None:
        """Test case for compare_text_request_id_get

        Return text comparing status.  Also return probability if one text is paraphrasing or translation of another
        """
        pass

    def test_compare_text_summarization_post(self) -> None:
        """Test case for compare_text_summarization_post

        Compare texts and detect if one is summarization of another
        """
        pass


if __name__ == '__main__':
    unittest.main()
