# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.detection_ocr_request import DetectionOcrRequest

class TestDetectionOcrRequest(unittest.TestCase):
    """DetectionOcrRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetectionOcrRequest:
        """Test DetectionOcrRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectionOcrRequest`
        """
        model = DetectionOcrRequest()
        if include_optional:
            return DetectionOcrRequest(
                language = '0',
                url = '',
                origin = '',
                original_name = '',
                saving_mode = 'Files',
                format = 'Unknown',
                min_length = 56
            )
        else:
            return DetectionOcrRequest(
                language = '0',
                format = 'Unknown',
        )
        """

    def testDetectionOcrRequest(self):
        """Test DetectionOcrRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
