# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.compare_text_response import CompareTextResponse

class TestCompareTextResponse(unittest.TestCase):
    """CompareTextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompareTextResponse:
        """Test CompareTextResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompareTextResponse`
        """
        model = CompareTextResponse()
        if include_optional:
            return CompareTextResponse(
                status = 'Continue',
                message = '',
                probability = 1.337,
                is_paraphrased_or_translated = True
            )
        else:
            return CompareTextResponse(
        )
        """

    def testCompareTextResponse(self):
        """Test CompareTextResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
