# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.models.formalize_text_request import FormalizeTextRequest

class TestFormalizeTextRequest(unittest.TestCase):
    """FormalizeTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormalizeTextRequest:
        """Test FormalizeTextRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormalizeTextRequest`
        """
        model = FormalizeTextRequest()
        if include_optional:
            return FormalizeTextRequest(
                language = '0',
                text = '',
                texts = [
                    ''
                    ],
                origin = ''
            )
        else:
            return FormalizeTextRequest(
                language = '0',
        )
        """

    def testFormalizeTextRequest(self):
        """Test FormalizeTextRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
