# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.trial_supported_formats import TrialSupportedFormats  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestTrialSupportedFormats(unittest.TestCase):
    """TrialSupportedFormats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrialSupportedFormats(self):
        """Test TrialSupportedFormats"""
        # inst = TrialSupportedFormats()

if __name__ == '__main__':
    unittest.main()
