# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.summarization_supported_formats import SummarizationSupportedFormats  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestSummarizationSupportedFormats(unittest.TestCase):
    """SummarizationSupportedFormats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummarizationSupportedFormats(self):
        """Test SummarizationSupportedFormats"""
        # inst = SummarizationSupportedFormats()

if __name__ == '__main__':
    unittest.main()
