# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.supported_conversions_formats import SupportedConversionsFormats  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestSupportedConversionsFormats(unittest.TestCase):
    """SupportedConversionsFormats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedConversionsFormats(self):
        """Test SupportedConversionsFormats"""
        # inst = SupportedConversionsFormats()

if __name__ == '__main__':
    unittest.main()
