# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.11.1
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.api.detect_api import DetectApi  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException


class TestDetectApi(unittest.TestCase):
    """DetectApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_rewriter_cloud.api.detect_api.DetectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_detect_document_post(self):
        """Test case for detect_document_post

        Detect paraphrasing in the document  # noqa: E501
        """
        pass

    def test_detect_document_request_id_get(self):
        """Test case for detect_document_request_id_get

        Return document detection status.  Also return probability of paraphrasing for the whole document and per paragraph  # noqa: E501
        """
        pass

    def test_detect_document_trial_post(self):
        """Test case for detect_document_trial_post

        Trial detect paraphrasing in the document  # noqa: E501
        """
        pass

    def test_detect_hc_get(self):
        """Test case for detect_hc_get

        Health check for detect all services.  # noqa: E501
        """
        pass

    def test_detect_text_post(self):
        """Test case for detect_text_post

        Detect paraphrasing in text  # noqa: E501
        """
        pass

    def test_detect_text_request_id_get(self):
        """Test case for detect_text_request_id_get

        Return text detection status.  Also return probability of paraphrasing for the whole text  # noqa: E501
        """
        pass

    def test_detect_text_trial_post(self):
        """Test case for detect_text_trial_post

        Trial detect paraphrasing in text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
