# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.api.info_api import InfoApi  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_rewriter_cloud.api.info_api.InfoApi()  # noqa: E501

    def test_info_available_languages_get(self):
        print(self.api.info_available_languages_get())
        pass


if __name__ == '__main__':
    unittest.main()
