# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.simplify_supported_fromats import SimplifySupportedFromats  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestSimplifySupportedFromats(unittest.TestCase):
    """SimplifySupportedFromats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimplifySupportedFromats(self):
        """Test SimplifySupportedFromats"""
        # inst = SimplifySupportedFromats()

if __name__ == '__main__':
    unittest.main()
