# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.api.formalize_api import FormalizeApi


class TestFormalizeApi(unittest.TestCase):
    """FormalizeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FormalizeApi()

    def tearDown(self) -> None:
        pass

    def test_formalize_document_post(self) -> None:
        """Test case for formalize_document_post

        Formalize document
        """
        pass

    def test_formalize_document_request_id_get(self) -> None:
        """Test case for formalize_document_request_id_get

        Return document formalizinh status.  Also return URLs for downloading of formalized document if paraphrasing was successful
        """
        pass

    def test_formalize_hc_get(self) -> None:
        """Test case for formalize_hc_get

        Health check for all simplify services.
        """
        pass

    def test_formalize_ocr_post(self) -> None:
        """Test case for formalize_ocr_post

        Formalize scanned image or document
        """
        pass

    def test_formalize_supported_conversions_get(self) -> None:
        """Test case for formalize_supported_conversions_get

        """
        pass

    def test_formalize_text_post(self) -> None:
        """Test case for formalize_text_post

        Formalize text
        """
        pass

    def test_formalize_text_request_id_get(self) -> None:
        """Test case for formalize_text_request_id_get

        Return text formalizing status.  Also return formalized text if paraphrasing was successful
        """
        pass


if __name__ == '__main__':
    unittest.main()
