# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.11.1
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.file_saving_mode import FileSavingMode  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestFileSavingMode(unittest.TestCase):
    """FileSavingMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileSavingMode(self):
        """Test FileSavingMode"""
        # inst = FileSavingMode()

if __name__ == '__main__':
    unittest.main()
