# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 25.3.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groupdocs_rewriter_cloud.api.generate_api import GenerateApi


class TestGenerateApi(unittest.TestCase):
    """GenerateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenerateApi()

    def tearDown(self) -> None:
        pass

    def test_generate_cover_letter_post(self) -> None:
        """Test case for generate_cover_letter_post

        Generate cover letter based on job description and optionally CV and cover letter that should be adopted to this offer
        """
        pass

    def test_generate_hc_get(self) -> None:
        """Test case for generate_hc_get

        Health check for generation services.
        """
        pass

    def test_generate_request_id_get(self) -> None:
        """Test case for generate_request_id_get

        Return generation status.  Also return generated result
        """
        pass

    def test_generate_test_exercise_post(self) -> None:
        """Test case for generate_test_exercise_post

        Generate test exercise based on job description and optionally CV
        """
        pass

    def test_generate_test_questions_post(self) -> None:
        """Test case for generate_test_questions_post

        Generate questions for technical interview based on job description and optionally CV
        """
        pass


if __name__ == '__main__':
    unittest.main()
