# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.4.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_rewriter_cloud
from groupdocs_rewriter_cloud.models.language_info import LanguageInfo  # noqa: E501
from groupdocs_rewriter_cloud.rest import ApiException

class TestLanguageInfo(unittest.TestCase):
    """LanguageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LanguageInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LanguageInfo`
        """
        model = groupdocs_rewriter_cloud.models.language_info.LanguageInfo()  # noqa: E501
        if include_optional :
            return LanguageInfo(
                id = 56, 
                code = '', 
                name = '', 
                actions = [
                    ''
                    ]
            )
        else :
            return LanguageInfo(
        )
        """

    def testLanguageInfo(self):
        """Test LanguageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
